### ISSUE TITLE
[BUG] Tracker: Gesture Handling

### ISSUE THREAD

**Issue by JaffaKetchup** [fleaflet/flutter_map#1529]
flutter_map makes extensive use of custom/raw gesture handling, outside of `GestureDetector`. Much of the code that does this was written in the first few releases, and has not been significantly changed since. However, new gestures have been added in on-top, with little thought to refactor and improve existing gestures (likely because this would/will take such a long time).

This has led to a single file of over 1000 lines of code managing pretty much all the gestures within FM. Obviously, this is not maintainable, and the perfect hiding place for bugs.

To make it worse, gesture handling at this low-level often differs slightly between platforms, which means that manual testing succeeds on one platform, but a bug occurs on another. There is a particular issue with iOS/MacOS in this regard.

To resolve the issues tracked here, a rewrite of the gesture handling system needs to be undertaken. Note that that bugs that occur as a result of gestures, but not directly as a mishandling of gestures (eg. #1682) are not tracked here.

```[tasklist]
### Issues
- [ ] https://github.com/fleaflet/flutter_map/issues/1395
- [ ] https://github.com/fleaflet/flutter_map/issues/1572
- [ ] https://github.com/fleaflet/flutter_map/issues/1429
- [ ] https://github.com/fleaflet/flutter_map/issues/1634
- [ ] https://github.com/fleaflet/flutter_map/issues/1644
- [ ] https://github.com/fleaflet/flutter_map/issues/1695
- [ ] https://github.com/fleaflet/flutter_map/issues/1723
- [ ] https://github.com/fleaflet/flutter_map/issues/1717
- [ ] https://github.com/fleaflet/flutter_map/issues/1602
- [ ] https://github.com/fleaflet/flutter_map/issues/1768
```

**Comment by josxha** [comment]
Expanded the issue tracker for all kind of bugs with the gesture system.
All issues on this list need to be revalidated after https://github.com/fleaflet/flutter_map/pull/1733 is merged.

**Comment by JaffaKetchup** [comment]
Any remaining gesture issues will be tracked individually. Platform specific issues will need to be re-evaluated.
