### ISSUE TITLE
[BUG] Tracker: Appeared in v6.0.1

### ISSUE THREAD

**Issue by josxha** [fleaflet/flutter_map#1736]
Bug tracker for reported bugs in the version 6.0.1 on pub.dev.
- Not listing more complex platform specific bugs caused by the gesture system.
- Most of them have already been fixed on the master branch and therefore are marked solved.

```[tasklist]
### Tasks
- [ ] https://github.com/fleaflet/flutter_map/issues/1723
- [ ] https://github.com/fleaflet/flutter_map/pull/1735
- [ ] https://github.com/fleaflet/flutter_map/issues/1725
- [ ] https://github.com/fleaflet/flutter_map/issues/1710
- [ ] https://github.com/fleaflet/flutter_map/pull/1712
```

**Comment by JaffaKetchup** [comment]
@josxha Is this issue good for deletion now?

**Comment by josxha** [comment]
Yes 👍
